theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "always"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

